pipeline{
    agent any
stages{
    stage("CODE"){
        steps{
            echo "This is cloning the code"
            git url:'https://github.com/umerali27/Declarative-CICD-Pipeline.git'
            echo "Cloned Successfully"
        }
    }
    stage("BUILD"){
        steps{
            echo "This is building the image"
            sh 'docker build -t devops-cicd-app ./app'
            echo "Successfully builded the image"
        }
    }
    stage("Deploy"){
        steps{
            echo "This is deploying the code"
            sh 'docker run -d -p 5000:5000 devops-cicd-app'
            echo "Successfully deployed the image"
        }
    }
    }

}
