pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/umerali27/Declarative-CICD-Pipeline.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-cicd-app ./app'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 5000:5000 devops-cicd-app'
            }
        }
    }
}
